import path from 'path';
import { build } from 'esbuild';
import { cleanPlugin } from 'esbuild-clean-plugin';

build({
  entryPoints: [
    'actions/createPrNextCheckSuite.ts',
    'actions/notifyPreReleaseResult.ts',
    'actions/notifyPrNextResult.ts',
  ],
  metafile: true,
  outdir: path.join(__dirname, './lib'),
  bundle: true,
  splitting: true,
  platform: 'node',
  format: 'esm',
  chunkNames: 'chunks/[name]-[hash]',
  target: 'node14',
  banner: {
    js: '// This file is generated by @opensumi/actions',
  },
  treeShaking: true,
  plugins: [cleanPlugin({})],
});
