name: "Run Script"
description: Run Specific Script

inputs:
  script:
    description: "script key, will generate full path: lib/${script}.js"
    required: true
    default: "main"
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: node16
  main: lib/${{ inputs.script }}.js
