name: "Publish NPM"
description: Publish OpenSumi Package

inputs:
  ref:
    description: "A valid ref(hash/tags/branch) on OpenSumi/core, eg: v2.20, main"
    required: true
    default: "main"
  npmToken:
    description: "NPM Token"
    required: true
  githubToken:
    description: "GitHub Token"
    required: true
  distTag:
    description: "distTag, next or rc"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        registry-url: "https://registry.npmjs.org"
    - uses: actions/checkout@v2
      with:
        repository: opensumi/core
        ref: ${{ inputs.ref }}
        path: workspace
    # 安装依赖并构建
    - name: Install dependencies & Build
      shell: bash
      working-directory: ./workspace
      run: |
        npm i
        npm run init

      # 使用 lerna publish 命令
      # --preid 指定前缀，确保版本唯一，前缀使用 $(date +%s) 生成类似  2.12.1-1640328423.0
      # --dist-tag 指定发布的 tag，默认是 latest
      # --no-push 指定不推送到远程仓库
      # --no-git-tag-version 不生成 git tag
      # --prepatch 指定发布的版本为 prepatch 版本, 只更新 patch 版本
      # --ignore-scripts 指定不执行脚本
      # --ignore-prepublish 忽略 pre-publish 脚本
    - name: Publish version
      shell: bash
      working-directory: ./workspace
      run: |
        lerna publish --exact --preid ${{ inputs.distTag }}-$(date +%s) --dist-tag ${{ inputs.distTag }} --force-publish='*' --no-push --no-git-tag-version prepatch --ignore-prepublish --ignore-scripts --no-private -y
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
        NODE_AUTH_TOKEN: ${{ inputs.npmToken }}

    - name: Adding markdown
      shell: bash
      working-directory: ./workspace
      if: success()
      run: |
        CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
        echo '### Released :rocket:' $CURRENT_VERSION >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo $CURRENT_VERSION >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo 'user input ref:' $INPUT_REF >> $GITHUB_STEP_SUMMARY
        echo '```log' >> $GITHUB_STEP_SUMMARY
        git log --oneline -1 >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
      env:
        INPUT_REF: ${{ inputs.ref }}
