// This file is generated by @opensumi/actions
import {
  createVersionText
} from "./chunks/chunk-H4EF3OOB.js";
import {
  call
} from "./chunks/chunk-SIMJG5HK.js";

// src/notifyPreReleaseResult.ts
call(async ({ github, context, core }) => {
  const issueBody = createVersionText("Pre-Release", process.env.CURRENT_VERSION, context);
  await github.rest.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: issueBody
  });
});
