// This file is generated by @opensumi/actions
import {
  createVersionText
} from "./chunks/chunk-H4EF3OOB.js";
import {
  call
} from "./chunks/chunk-SIMJG5HK.js";

// src/notifyRCResult.ts
call(async ({ github, context, core }) => {
  const commentBody = createVersionText("Release Candidate", process.env.CURRENT_VERSION, context);
  await github.rest.repos.createCommitComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: commentBody,
    commit_sha: process.env.INPUT_REF
  });
});
