name: 'Get Bot Token'
description: Get Bot Token

inputs:
  token-server:
    description: token server
    required: true
  flag:
    description: current app
    required: true

outputs:
  token:
    description: 'Bot Token'

runs:
  using: 'node16'
  main: ../lib/getAccessToken.js
