name: 'Get Bot Token'
description: Get Bot Token

inputs:
  token-server:
    description: token server
    required: true
  flag:
    description: current app
    required: true

outputs:
  token:
    description: 'Bot Token'

runs:
  using: 'node16'
  main: ../lib/bot-token/get-access-token.js
  post: ../lib/bot-token/revoke-token.js
