name: 'Get Bot Token'
description: Get Bot Token

inputs:
  token-server:
    description: token server
    required: true
  flag:
    description: current app
    required: true

runs:
  using: 'composite'
  steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Get Bot Token
      shell: bash
      id: get-token
      run: |
        node ${{ github.action_path }}/../lib/getAccessToken.js
      with:
        token-server: ${{ inputs.token-server }}
        flag: ${{ inputs.flag }}
