name: CodeBlitz Release NEXT Version

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Pull Request Number'
        required: true

jobs:
  next-version:
    name: CodeBlitz Next Version
    environment: next
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: opensumi/actions/bot-token@main
        id: bot-token
        with:
          token-server: ${{ secrets.BOT_TOKEN_SERVER }}
          flag: ${{ secrets.BOT_FLAG }}
      
      - uses: opensumi/actions/parse-pr-data@main
        id: parse-pr-data
        with:
          owner: opensumi
          repo: codeblitz
          pull_number: ${{ inputs.pull_number }}

      # Checkout to specific branch
      - uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ steps.parse-pr-data.outputs.head_sha }}
          repository: opensumi/codeblitz
          token: ${{ steps.bot-token.outputs.token }}

      - uses: opensumi/actions/.github/actions/run-script@main
        with:
          script: 'createPrNextCheckSuite'
        env:
          STATUS: start
          OWNER: opensumi
          REPO: codeblitz
          HEAD_SHA: ${{ steps.parse-pr-data.outputs.head_sha }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Get yarn cache directory path
        id: yarn_cache_dir_path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn_cache
        with:
          path: ${{ steps.yarn_cache_dir_path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 安装依赖并构建
      - name: Install dependencies & Build
        run: |
          yarn install --immutable
          yarn run init
          yarn run build:all

      - name: Setup .yarnrc.yml
        run: |
          yarn config set -H npmRegistryServer "https://registry.npmjs.org"
          yarn config set -H npmAlwaysAuth true
          yarn config set -H npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish prepatch version
        run: |
          lerna publish --exact --preid next-$(date +%s) --dist-tag next --force-publish='*' --no-push --no-git-tag-version prepatch --ignore-prepublish --ignore-scripts --no-private -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Adding markdown
        if: success()
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          CURRENT_COMMIT=$(git rev-parse --short HEAD)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
          echo "CURRENT_COMMIT=${CURRENT_COMMIT}" >> $GITHUB_ENV
          echo '### Released :rocket:' $CURRENT_VERSION >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo $CURRENT_VERSION >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo 'user input ref:' $INPUT_REF >> $GITHUB_STEP_SUMMARY
          echo '```log' >> $GITHUB_STEP_SUMMARY
          git log --oneline -1 >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo 'SUMMARY<<EOF' >> $GITHUB_ENV
          cat $GITHUB_STEP_SUMMARY >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          INPUT_REF: ${{ github.event.inputs.ref }}
      # 发布完成后，在 issue 中评论，并更新 checkRun 状态
      - uses: opensumi/actions/.github/actions/run-script@main
      if: success()
      with:
        script: 'notifyPrNextResult'
      env:
        OWNER: opensumi
        REPO: codeblitz
        ISSUE_NUMBER: ${{ inputs.pull_number }}
      # 发布失败后，更新 checkRun 状态
      - uses: opensumi/actions/.github/actions/run-script@main
        if: failure()
        with:
          script: 'createPrNextCheckSuite'
        env:
          STATUS: end
          OWNER: opensumi
          REPO: codeblitz
          HEAD_SHA: ${{ steps.parse-pr-data.outputs.head_sha }}
