name: Backport Pull Request To

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: 'Pull Request Number'
        required: true
      target_branch:
        description: 'Target Branch'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.OS_BOT_TOKEN }}

jobs:
  backport:
    runs-on: ubuntu-latest
    name: backport
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn

      - name: Parse Pull Request ${{ inputs.pull_number }}
        id: parse-pr-data
        run: |
          yarn tsx ./src/backportPrTo.ts
        env:
          OWNER: opensumi
          REPO: core
          PULL_NUMBER: ${{ inputs.pull_number }}

      # 这个 action checkout 出的代码可以 push 到远程
      - name: Checkout SHA
        uses: actions/checkout@v3
        with:
          repository: opensumi/core
          ref: ${{ steps.parse-pr-number.outputs.sha }}
          path: workspace
          token: ${{ secrets.OS_BOT_TOKEN }}

      - run: |
          cd workspace
          branch="backport/queue/${{ inputs.pull_number }}-$(date +"%Y%m%d%H%M%S")"
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout -b $branch
          git push -u origin $branch
          export PR_FROM=$branch
          cd ..
          yarn tsx ./src/backportPrTo.ts
        env:
          OWNER: opensumi
          REPO: core
          PULL_NUMBER: ${{ inputs.pull_number }}
          TARGET_BRANCH: ${{ inputs.target_branch }}
          GITHUB_TOKEN: ${{ secrets.OS_BOT_TOKEN }}
