name: Backport Pull Request To

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: 'Pull Request Number'
        required: true
      target_branch:
        description: 'Target Branch'
        required: true

env:
  CODEBASE_PATH: 'workspace'

jobs:
  backport:
    runs-on: ubuntu-latest
    name: backport
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn

      - uses: opensumi/actions/bot-token@main
        id: bot-token
        with:
          token-server: ${{ secrets.BOT_TOKEN_SERVER }}
          flag: ${{ secrets.BOT_FLAG }}

      - name: Parse Pull Request ${{ inputs.pull_number }}
        id: parse-pr-data
        run: |
          yarn tsx ./src/backportPrTo.ts
        env:
          OWNER: opensumi
          REPO: core
          PULL_NUMBER: ${{ inputs.pull_number }}
      # 这个 action checkout 出的代码可以 push 到远程
      - name: Checkout SHA
        uses: actions/checkout@v3
        with:
          repository: opensumi/core
          ref: ${{ inputs.target_branch }}
          path: ${{ env.CODEBASE_PATH }}
          token: ${{ steps.bot-token.outputs.token }}

      - name: Pick And Push
        run: |
          git config --global user.name "opensumi[bot]"
          git config --global user.email "99156626+opensumi[bot]@users.noreply.github.com"

          yarn tsx ./src/backportPrTo.ts
        env:
          OWNER: opensumi
          REPO: core
          PULL_NUMBER: ${{ inputs.pull_number }}
          TARGET_BRANCH: ${{ inputs.target_branch }}
          GITHUB_TOKEN: ${{ steps.bot-token.outputs.token }}
