name: CodeBlitz Release Next Version By Ref

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'A valid ref, eg: v3.xx, main'
        required: true
        default: 'main'

jobs:
  next-version:
    name: Next Version
    environment: next
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: opensumi/actions/bot-token@main
        id: bot-token
        with:
          token-server: ${{ secrets.BOT_TOKEN_SERVER }}
          flag: ${{ secrets.BOT_FLAG }}

      # Checkout 到 PR 对应分支
      - uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ inputs.ref }}
          repository: opensumi/codeblitz
          token: ${{ steps.bot-token.outputs.token }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Set output
        id: yarn_cache_dir_path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn_cache
        with:
          path: ${{ steps.yarn_cache_dir_path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # 安装依赖并构建
      - name: Install dependencies & Build
        run: |
          yarn install --immutable
          yarn run init
          yarn run build:all

      - name: Setup git & yarn
        run: |
          git config --global user.name "opensumi[bot]"
          git config --global user.email "99156626+opensumi[bot]@users.noreply.github.com"

          yarn config set -H npmRegistryServer "https://registry.npmjs.org"
          yarn config set -H npmAlwaysAuth true
          yarn config set -H npmAuthToken $NPM_AUTH_TOKEN

          CURRENT_COMMIT=$(git rev-parse --short HEAD)
          echo "CURRENT_COMMIT=${CURRENT_COMMIT}" >> $GITHUB_ENV
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish next version
        uses: opensumi/actions/.github/actions/run-script@main
        with:
          script: 'lerna-publish/index'
        env:
          HEAD_REF: ${{ inputs.ref }}
          GH_TOKEN: ${{ env.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Adding markdown
        if: success()
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
          echo '### Released :rocket:' $CURRENT_VERSION >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo $CURRENT_VERSION >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo 'user input ref:' $INPUT_REF >> $GITHUB_STEP_SUMMARY
          echo '```log' >> $GITHUB_STEP_SUMMARY
          git log --oneline -1 >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo 'SUMMARY<<EOF' >> $GITHUB_ENV
          cat $GITHUB_STEP_SUMMARY >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          INPUT_REF: ${{ github.event.inputs.ref }}
      - uses: opensumi/actions/.github/actions/run-script@main
        if: success()
        with:
          script: 'notifyNextResult'
        env:
          OWNER: opensumi
          REPO: codeblitz
