name: Monthly Report

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'Specify the time of the report'
        required: false

jobs:
  report:
    runs-on: ubuntu-latest
    name: report
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn

      - uses: opensumi/actions/bot-token@main
        id: bot-token
        with:
          token-server: ${{ secrets.BOT_TOKEN_SERVER }}
          flag: ${{ secrets.BOT_FLAG }}

      - name: Monthly Report
        run: |
          yarn tsx ./src/monthlyReport.ts
        env:
          TARGET_TIME: ${{ inputs.time }}
