name: OpenSumi sync to npmmirror

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Poll specific version'
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    name: sync
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Sync
        run: |
          yarn
          yarn sync ${{ github.event.inputs.version }}
