name: for test

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    name: sync
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: CURRENT_VERSION
        if: success()
        run: |
          echo "CURRENT_VERSION=1234" >> $GITHUB_ENV
          echo "CURRENT_COMMIT=b038058" >> $GITHUB_ENV
          echo "SUMMARY=this is summary" >> $GITHUB_ENV
      - uses: opensumi/actions/.github/actions/run-script@main
        if: success()
        with:
          script: "notifyRCResult"
